security:
    providers:
        app_user_provider:
            entity:
                class: App\Domain\Entity\User
                property: username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            lazy: true
            provider: app_user_provider
            logout:
                path: logout
            json_login:
                check_path: /login

    encoders:
        App\Domain\Entity\User:
            algorithm: bcrypt
